defaults: 
  - model_defaults # Inherit model_defaults arguments

# --------------------------
#         Model
# --------------------------
model: "linear_head" 
# Only applicable for synthetic dataset
use_residuals_from_data: false # Whether to use the residuals from the dataset (if available)