experiment_name: 'experiments' # Name of the experiment
experiment_dir: './experiments/'  # Directory to potentially save the model to

seed: 0 # Random seed
workers: 2 # Number of workers for data loading
save_model: False # Whether to save the model. Set to True for inspecting models post training [True, False]
train_only: False # Whether to train the model only and exit before performing interventions [True, False]
incomplete: False
run_inference: False
run_interventions: False
num_attribute_groups_remove: 14 # Number of attribute groups to remove when creating incomplete datasets. Only used if incomplete is True. Should be between 0 and 28 for CUB.
remove_attribute_groups: False # Whether to create an incomplete dataset by removing entire attribute groups, or by randomly removing individual attributes across groups. Only used if incomplete is True. [True, False]
ratio_attributes_remove: 0.5 # Ratio of attributes to remove when creating incomplete datasets by randomly removing individual attributes across groups. Only used if incomplete is True and remove_attribute_groups is False. Should be between 0 and 1.


logging:
  project: 'SCBM' # Name of the wandb project
  mode: 'disabled' # Whether to log to wandb [online, offline, disabled]
  entity: "your_entity" # Your wandb entity

inference:
  ex_name: null
